apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-statefulsets
rules:
- apiGroups: ["apps"]
  resources:
    - "statefulsets"
    - "statefulsets/scale"
  verbs:
    - "get"
    - "list"
    - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-jobs
rules:
- apiGroups: ["batch"]
  resources:
    - "jobs"
  verbs:
    - "get"
    - "list"
    - "create"
    - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-statefulsets
subjects:
- kind: ServiceAccount
  name: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-statefulsets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-jobs
subjects:
- kind: ServiceAccount
  name: backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-jobs
