#!/bin/bash

echo "$POSTGRESQL_SERVICE_HOST:$POSTGRESQL_SERVICE_PORT_POSTGRESQL:$POSTGRESQL_DATABASE:$POSTGRESQL_USER:$POSTGRESQL_PASSWORD" > $HOME/.pgpass
chmod 600 $HOME/.pgpass

psql -h $POSTGRESQL_SERVICE_HOST -d $POSTGRESQL_DATABASE -U $POSTGRESQL_USER < /mnt/init/init-db.sql


