apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: infra
  name: 50-motd
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,VGhpcyBpcyBhIGN1c3RvbSBtZXNzYWdlIG9mIHRoZSBkYXkgZmlsZS4K
        filesystem: root
        mode: 0644
        path: /etc/motd
